export enum DateRuleType {
	None = "None",
	CustomRange = "CustomRange",
	LastWeek = "LastWeek",
	LastMonth = "LastMonth",
	LastYear = "LastYear",
	YearToDate = "YearToDate",
	QuarterToDate = "QuarterToDate",
	MonthToDate = "MonthToDate",
	AllTime = "AllTime",
	Yesterday = "Yesterday",
	Today = "Today",
	ThisMonth = "ThisMonth",
	ThisQuarter = "ThisQuarter",
	ThisYear = "ThisYear",
	PreviousMonth = "PreviousMonth",
	PreviousQuarter = "PreviousQuarter",
	PreviousYear = "PreviousYear",
	NextMonth = "NextMonth",
	NextQuarter = "NextQuarter",
	NextYear = "NextYear",
	TrailingTwelveMonths = "TrailingTwelveMonths"
}
