export enum ChartType {
    Area = "Area",
    Bar = "Bar",
    Bubble = "Bubble",
    BulletGraph = "BulletGraph",
    Candlestick = "Candlestick",
    Choropleth = "Choropleth",
    CircularGauge = "CircularGauge",
    Column = "Column",
    Combo = "Combo",
    Custom = "Custom",
    Doughnut = "Doughnut",
    Funnel = "Funnel",
    Grid = "Grid",
    Image = "Image",
    KpiTarget = "KpiTarget",
    KpiTime = "KpiTime",
    Line = "Line",
    LinearGauge = "LinearGauge",
    OHLC = "OHLC",
    Pie = "Pie",
    Pivot = "Pivot",
    Radial = "Radial",
    Scatter = "Scatter",
    ScatterMap = "ScatterMap",
    Sparkline = "Sparkline",
    Spline = "Spline",
    SplineArea = "SplineArea",
    StackedArea = "StackedArea",
    StackedBar = "StackedBar",
    StackedColumn = "StackedColumn",
    StepArea = "StepArea",
    StepLine = "StepLine",
    Text = "Text",
    TextBox = "TextBox",
    TextView = "TextView",
    TimeSeries = "TimeSeries",
    TreeMap = "TreeMap",
    Unknown = "Unknown",
}

/*
These options are used internally to map to the JSON properties on the VisualizationSettings element of the RDASH schema. 
DO NOT USE IN PUBLIC API
*/
export enum RdashChartType {
    Column = "Column",
    Line = "Line",
    Bar = "Bar",
    Area = "Area",
    Spline = "Spline",
    SplineArea = "SplineArea",
    StepArea = "StepArea",
    StepLine = "StepLine",
    Composite = "Composite",
    Bubble = "Bubble",
    Candlestick = "Candlestick",
    OHLC = "OHLC",
    Pie = "Pie",
    RadialLines = "RadialLines",
    Scatter = "Scatter",
    StackedColumn = "StackedColumn",
    StackedArea = "StackedArea",
    StackedBar = "StackedBar",
    Doughnut = "Doughnut",
    Funnel = "Funnel",
    TimeSeries = "TimeSeries",
}
